Background Calculations
LSSTDESC/CCL pull request #1149
Opened 2023-12-21 07:15 UTC by hsinfan1996

Merge existing distances_v3 branch into master (different from PR #1066 ). Closes issue #954 andd #408 .

2023-12-21 12:31 UTC, hsinfan1996 commented on pyccl/_core/parameters/parameters_base.py
> +    YEAR = 365.256_363_004 * DAY
This part is ad-hoc. We can port all constants from C to Python level.

2023-12-21 14:24 UTC, hsinfan1996 commented
@nikosarcevic I've done merging the master branch into the revived distances_v3. Now you can try the new functions and see if the calculations are correct and maybe modify the code if you want.

2023-12-22 17:59 UTC, damonge commented
@hsinfan1996 let me know when you'd like me to review this. Right now I see the tests are still failing, but happy to help.

2023-12-26 16:28 UTC, hsinfan1996 commented
@damonge This is ready for review. Is there a way to fix the tests on macOS? I don't know why sometimes they passed but sometimes not.

2023-12-28 05:57 UTC, hsinfan1996 commented
> @damonge This is ready for review. Is there a way to fix the tests on macOS? I don't know why sometimes they passed but sometimes not.

From my observation, faster test runs (typically < 25 min) on macOS will pass, slower ones (~35 min) will not. The weird thing is that the failed tests are not timed, but it is good to know that the problem is not likely caused by the code.

2024-01-02 09:06 UTC, damonge requested changes
Thanks a lot @hsinfan1996 (and @nikfilippas for the initial implementation). Some comments below.

2024-01-02 09:06 UTC, damonge commented on pyccl/background.py
> +
```suggestion
    See Eq. 29 in `Hogg 2000 <https://arxiv.org/abs/astro-ph/9905116>`_.
    
```

2024-01-02 09:06 UTC, damonge commented on pyccl/cosmology.py
> +class CosmologyData:
Can you add a comment here for future developers that the aim is for this class to be used to port other background calculators from C to python?

Also, we should make it a private class (`_CosmologyData`), and perhaps relabel it to `_CosmologyBackgroundData` to make it clearer what it's supposed to hold.

2024-01-02 09:06 UTC, damonge commented on pyccl/tests/test_background.py
> +
`comoving_volume_element` isn't being tested anywhere, right?

2024-01-02 16:29 UTC, damonge commented on pyccl/tests/test_background.py
> +
OK, yes, good point.

2024-01-02 16:31 UTC, damonge approved these changes
LGTM!

2024-01-02 16:37 UTC, merged